######################################################################
# Automatically generated by qmake (2.01a) vr 16. mrt 13:27:39 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
RC_FILE = fractal.rc

# Input
HEADERS += fractal.h fractalwidget.h mainwindow.h fractalrenderer.h
SOURCES += fractal.cpp fractalwidget.cpp main.cpp mainwindow.cpp fractalrenderer.cpp
